name: Auto Request Review
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Add Manager as Reviewer
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['owaisazad']
            })